# image will be published to ghcr.io/<user>/<name>
name: kaminari-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-asus
image-version: latest

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
    install:
      - code
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - rocm-hip
      - rocm-opencl
      - rocm-smi
    remove:
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.discordapp.Discord
        - com.ulduzsoft.Birdtray
        - com.github.flxzt.rnote
        - md.obsidian.Obsidian
        - org.mozilla.Thunderbird
        - org.signal.Signal
        - us.zoom.Zoom
      remove:
  # this sets up the proper policy & signing files for signed images to work fully
  - type: signing

