# image will be published to ghcr.io/<user>/<name>
name: kaminari-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-asus
image-version: latest

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: /

  # - type: rpm-ostree
  #   repos:
  #   install:
  #   remove:

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.libreoffice.LibreOffice
        - com.discordapp.Discord
        - com.ulduzsoft.Birdtray
        - com.github.flxzt.rnote
        - md.obsidian.Obsidian
        - org.signal.Signal
        - us.zoom.Zoom
        - it.mijorus.gearlever
        - com.github.neithern.g4music
      # remove:

  # this sets up the proper policy & signing files for signed images to work fully
  - type: signing

